# Maven
# Build your Java project and run tests with Apache Maven.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/java

trigger:
- master

pool:
  vmImage: 'windows-2019'

stages:
- stage: Maven_And_Analysis
  jobs:
  - job: Maven_Compile_Job
    displayName: 'Compile ADAS-Park Assist App Code'
    
    steps:
     
    - task: Bash@3
      displayName: 'Set SonarQube Environment Variables'
      inputs:
        targetType: 'inline'
        script: |
          echo "##vso[task.setvariable variable=SONAR_HOST_URL]$(SONAR_HOST_URL)"
          echo "##vso[task.setvariable variable=SONAR_TOKEN]$(SONAR_TOKEN)"
    - task: Maven@3
      inputs:
        mavenPomFile: 'pom.xml'
        goals: 'compile'
        publishJUnitResults: true
        testResultsFiles: '**/surefire-reports/TEST-*.xml'
        javaHomeOption: 'JDKVersion'
        jdkVersionOption: '1.17'
        mavenVersionOption: 'Default'
        mavenOptions: '-Xmx3072m'
        mavenAuthenticateFeed: false
        effectivePomSkip: false
        sonarQubeRunAnalysis: true
        sqMavenPluginVersionChoice: 'latest'

    - task: Maven@3
      displayName: 'Run SonarQube Analysis'
      inputs:
        mavenPomFile: 'pom.xml'
        goals: 'verify org.sonarsource.scanner.maven:sonar-maven-plugin:sonar'
        options: '-Dsonar.host.url=$(SONAR_HOST_URL) -Dsonar.login=$(SONAR_TOKEN)'
        javaHomeOption: 'JDKVersion'
        jdkVersionOption: '1.17'
        mavenVersionOption: 'Default'
        mavenOptions: '-Xmx3072m'
        mavenAuthenticateFeed: false
        effectivePomSkip: false
