trigger:
  branches:
    include:
      - master 

pool:
  vmImage: 'windows-2019'

variables:
  - group: secrets

stages:
- stage: Maven_And_Analysis
  jobs:
  - job: Maven_Compile_Job
    displayName: 'Compile ADAS-Park Assist App Code'
    steps:
    - script: |
        mvn clean
        mvn dependency:tree
      displayName: 'Clean and Analyze Dependencies'

    - task: Maven@3
      inputs:
        mavenPomFile: 'pom.xml'
        goals: 'compile'
        publishJUnitResults: false
        javaHomeOption: 'JDKVersion'
        jdkVersionOption: '1.17'
        mavenVersionOption: 'Default'
        mavenOptions: '-Xmx3072m'
        mavenAuthenticateFeed: false
        effectivePomSkip: false

    - task: SonarQubePrepare@4
      inputs:
        SonarQube: 'Sonar_Connect'  # Name of the SonarQube service connection
        scannerMode: 'CLI'
        configMode: 'manual'
        cliProjectKey: 'ADAS'
        cliProjectName: 'ADAS'
        extraProperties: |
          sonar.exclusions=**/*.bin

    - task: Maven@3
      inputs:
        mavenPomFile: 'pom.xml'
        goals: 'verify sonar:sonar'
        publishJUnitResults: true
        testResultsFiles: '**/surefire-reports/TEST-*.xml'
        javaHomeOption: 'JDKVersion'
        jdkVersionOption: '1.17'
        mavenVersionOption: 'Default'
        mavenOptions: '-Xmx3072m'
        mavenAuthenticateFeed: false
        effectivePomSkip: false
